import type { KeyboardEventHandler, RefObject } from 'react';
import type { Artifact } from '../../../../../../types';
import type { LoadState } from '../types';

export interface IframeRenderedViewProps {
  artifact: Artifact | null;
  artifactHtml: string;
  artifactId: string | null;
  cancel: () => void;
  canGoBack: boolean;
  canGoForward: boolean;
  commit: () => void;
  discardSnapshot: string | null;
  draftUrl: string;
  faviconUrl?: string;
  frameHostRef: RefObject<HTMLDivElement>;
  generating: boolean;
  handleOpenExternal: () => void;
  handleKeyDown: KeyboardEventHandler<HTMLInputElement>;
  handleGoBack: () => void;
  handleGoForward: () => void;
  handlePickDomElement: () => Promise<void> | void;
  handlePickReviewElement: () => Promise<void> | void;
  handleRegenerate: () => Promise<void> | void;
  handleReload: () => void;
  html: string;
  isArtifactMode: boolean;
  isResizing?: boolean;
  loadError: string | null;
  loadState: LoadState;
  localUrl: string;
  mode: string;
  nodeId: string;
  openArtifact: (workspaceId: string, artifactId: string) => void;
  domPickerActive: boolean;
  reviewPickerActive: boolean;
  readOnly: boolean;
  savedPrompt: string;
  setDraftUrl: (value: string) => void;
  setEditing: (editing: boolean) => void;
  onWakeWebview: () => void;
  renderIframeRef: RefObject<HTMLIFrameElement>;
  shouldMountInlineFrame: boolean;
  streamIframeRef: RefObject<HTMLIFrameElement>;
  streamingActive: boolean;
  webviewDiscarded: boolean;
  title?: string;
  url: string;
  webviewHostRef: RefObject<HTMLDivElement>;
  webviewKey: number;
  workspaceId?: string;
}
