import type { PluginMarketListing } from '../../shared/plugin-market';

/**
 * Small, reviewed launch catalog. Agent Plugins does not define discovery,
 * branding, trust, or marketplace metadata, so Pulse owns those decisions.
 * Every entry below points at a package whose root or subdirectory declares
 * the canonical Agent Plugins 1.0 schema.
 */
export const PUBLIC_PLUGIN_CATALOG: readonly PluginMarketListing[] = [
  {
    id: 'exa',
    name: 'Exa',
    description: 'Search the web and code, crawl pages, and run focused research.',
    author: { name: 'Exa', url: 'https://exa.ai' },
    license: 'MIT',
    category: 'Research',
    featured: true,
    visibility: 'public',
    sourceFormat: 'agent-plugin',
    source: { kind: 'git', url: 'https://github.com/exa-labs/exa-mcp-server.git', ref: '15ffb50519e719dc791cdc750ce5ed1934c0a1ed' },
    iconKey: 'exa',
    capabilities: { skillCount: 2, mcpServerCount: 1, hasPulseExtension: false },
    installState: 'available',
  },
  {
    id: 'transcriptapi',
    name: 'TranscriptAPI',
    description: 'Read YouTube transcripts, search videos, and browse channels and playlists.',
    author: { name: 'Zero Point Studio', url: 'https://transcriptapi.com' },
    license: 'MIT',
    category: 'Research',
    featured: true,
    visibility: 'public',
    sourceFormat: 'agent-plugin',
    source: { kind: 'git', url: 'https://github.com/ZeroPointRepo/youtube-mcp.git', ref: '7fa7d13ee2a8740396d51ab040170214de1e2105' },
    iconKey: 'transcriptapi',
    capabilities: { skillCount: 1, mcpServerCount: 1, hasPulseExtension: false },
    installState: 'available',
  },
  {
    id: 'arcade',
    name: 'Arcade',
    description: 'Connect Gmail, Calendar, Slack, Notion, Spotify, and other apps.',
    author: { name: 'Arcade.dev', url: 'https://www.arcade.dev' },
    license: 'Apache-2.0',
    category: 'Productivity',
    featured: true,
    visibility: 'public',
    sourceFormat: 'agent-plugin',
    source: { kind: 'git', url: 'https://github.com/arcadeai-labs/arcade.git', ref: '6d496e3d8dfc9ded786f8ae4ab71175e8d8ff003' },
    iconKey: 'arcade',
    capabilities: { skillCount: 3, mcpServerCount: 1, hasPulseExtension: false },
    installState: 'available',
  },
  {
    id: 'resend',
    name: 'Resend',
    description: 'Send and receive email, build templates, and follow deliverability practices.',
    author: { name: 'Resend', url: 'https://resend.com' },
    license: 'MIT',
    category: 'Productivity',
    featured: false,
    visibility: 'public',
    sourceFormat: 'agent-plugin',
    source: { kind: 'git', url: 'https://github.com/resend/resend-skills.git', ref: '2a69b9f39a16c043cbfad45fbfa3c141bd27b050' },
    iconKey: 'resend',
    capabilities: { skillCount: 5, mcpServerCount: 1, hasPulseExtension: false },
    installState: 'available',
  },
  {
    id: 'opnform',
    name: 'OpnForm',
    description: 'Create and preview forms, manage them, and read their submissions.',
    author: { name: 'OpnForm', url: 'https://opnform.com' },
    license: 'AGPL-3.0-or-later',
    category: 'Productivity',
    featured: false,
    visibility: 'public',
    sourceFormat: 'agent-plugin',
    source: {
      kind: 'git',
      url: 'https://github.com/OpnForm/OpnForm.git',
      ref: 'e4bb538a2ed9f8480260abca3659150b74e9ce87',
      subdir: 'plugins/opnform',
    },
    iconKey: 'opnform',
    capabilities: { skillCount: 1, mcpServerCount: 1, hasPulseExtension: false },
    installState: 'available',
  },
  {
    id: 'mobbin',
    name: 'Mobbin',
    description: 'Search real product screens, flows, and website sections. Requires a paid Mobbin plan.',
    author: { name: 'Mobbin', url: 'https://mobbin.com' },
    license: 'MIT',
    category: 'Design',
    featured: false,
    visibility: 'public',
    sourceFormat: 'agent-plugin',
    source: { kind: 'git', url: 'https://github.com/mobbin/mobbin-agent-plugin.git', ref: '8539d47c3f3f501fabf11283eaa6e1b4161f00b1' },
    iconKey: 'mobbin',
    capabilities: { skillCount: 0, mcpServerCount: 1, hasPulseExtension: false },
    installState: 'available',
  },
  {
    id: 'mcp-apps-basic-react',
    name: 'MCP Apps · Basic React',
    description: 'Official MCP Apps starter UI showing tool input, structured output, and app-to-server calls.',
    author: { name: 'Model Context Protocol', url: 'https://github.com/modelcontextprotocol/ext-apps' },
    license: 'MIT',
    category: 'Developer',
    featured: false,
    visibility: 'public',
    sourceFormat: 'agent-plugin',
    source: {
      kind: 'git',
      url: 'https://github.com/hua-bang/pulse-agent.git',
      ref: 'dab497a6ae5e64b32f4ed5291d243e173d1f8b26',
      subdir: 'examples/agent-plugins/mcp-apps-basic-react',
    },
    iconKey: 'plugin',
    capabilities: { skillCount: 0, mcpServerCount: 1, hasPulseExtension: false },
    installState: 'available',
  },
  {
    id: 'mcp-apps-map',
    name: 'MCP Apps · Interactive Map',
    description: 'Official interactive 3D globe with geocoding and OpenStreetMap tiles.',
    author: { name: 'Model Context Protocol', url: 'https://github.com/modelcontextprotocol/ext-apps' },
    license: 'MIT',
    category: 'Developer',
    featured: false,
    visibility: 'public',
    sourceFormat: 'agent-plugin',
    source: {
      kind: 'git',
      url: 'https://github.com/hua-bang/pulse-agent.git',
      ref: 'dab497a6ae5e64b32f4ed5291d243e173d1f8b26',
      subdir: 'examples/agent-plugins/mcp-apps-map',
    },
    iconKey: 'plugin',
    capabilities: { skillCount: 0, mcpServerCount: 1, hasPulseExtension: false },
    installState: 'available',
  },
  {
    id: 'mcp-apps-threejs',
    name: 'MCP Apps · Three.js',
    description: 'Official Three.js visualization app for rendering interactive 3D scenes.',
    author: { name: 'Model Context Protocol', url: 'https://github.com/modelcontextprotocol/ext-apps' },
    license: 'MIT',
    category: 'Developer',
    featured: false,
    visibility: 'public',
    sourceFormat: 'agent-plugin',
    source: {
      kind: 'git',
      url: 'https://github.com/hua-bang/pulse-agent.git',
      ref: 'dab497a6ae5e64b32f4ed5291d243e173d1f8b26',
      subdir: 'examples/agent-plugins/mcp-apps-threejs',
    },
    iconKey: 'plugin',
    capabilities: { skillCount: 0, mcpServerCount: 1, hasPulseExtension: false },
    installState: 'available',
  },
];
