import type { PluginMarketListing } from '../../shared/plugin-market';

/**
 * Small, reviewed launch catalog. Agent Plugins does not define discovery,
 * branding, trust, or marketplace metadata, so Pulse owns those decisions.
 * Every entry below points at a package whose root or subdirectory declares
 * the canonical Agent Plugins 1.0 schema.
 */
export const PUBLIC_PLUGIN_CATALOG: readonly PluginMarketListing[] = [
  {
    id: 'exa',
    name: 'Exa',
    description: 'Search the web and code, crawl pages, and run focused research.',
    author: { name: 'Exa', url: 'https://exa.ai' },
    license: 'MIT',
    category: 'Research',
    featured: true,
    visibility: 'public',
    sourceFormat: 'agent-plugin',
    source: { kind: 'git', url: 'https://github.com/exa-labs/exa-mcp-server.git' },
    iconKey: 'exa',
    capabilities: { skillCount: 2, mcpServerCount: 1, hasPulseExtension: false },
    installState: 'available',
  },
  {
    id: 'transcriptapi',
    name: 'TranscriptAPI',
    description: 'Read YouTube transcripts, search videos, and browse channels and playlists.',
    author: { name: 'Zero Point Studio', url: 'https://transcriptapi.com' },
    license: 'MIT',
    category: 'Research',
    featured: true,
    visibility: 'public',
    sourceFormat: 'agent-plugin',
    source: { kind: 'git', url: 'https://github.com/ZeroPointRepo/youtube-mcp.git' },
    iconKey: 'transcriptapi',
    capabilities: { skillCount: 1, mcpServerCount: 1, hasPulseExtension: false },
    installState: 'available',
  },
  {
    id: 'arcade',
    name: 'Arcade',
    description: 'Connect Gmail, Calendar, Slack, Notion, Spotify, and other apps.',
    author: { name: 'Arcade.dev', url: 'https://www.arcade.dev' },
    license: 'Apache-2.0',
    category: 'Productivity',
    featured: true,
    visibility: 'public',
    sourceFormat: 'agent-plugin',
    source: { kind: 'git', url: 'https://github.com/arcadeai-labs/arcade.git' },
    iconKey: 'arcade',
    capabilities: { skillCount: 3, mcpServerCount: 1, hasPulseExtension: false },
    installState: 'available',
  },
  {
    id: 'resend',
    name: 'Resend',
    description: 'Send and receive email, build templates, and follow deliverability practices.',
    author: { name: 'Resend', url: 'https://resend.com' },
    license: 'MIT',
    category: 'Productivity',
    featured: false,
    visibility: 'public',
    sourceFormat: 'agent-plugin',
    source: { kind: 'git', url: 'https://github.com/resend/resend-skills.git' },
    iconKey: 'resend',
    capabilities: { skillCount: 5, mcpServerCount: 1, hasPulseExtension: false },
    installState: 'available',
  },
  {
    id: 'opnform',
    name: 'OpnForm',
    description: 'Create and preview forms, manage them, and read their submissions.',
    author: { name: 'OpnForm', url: 'https://opnform.com' },
    license: 'AGPL-3.0-or-later',
    category: 'Productivity',
    featured: false,
    visibility: 'public',
    sourceFormat: 'agent-plugin',
    source: {
      kind: 'git',
      url: 'https://github.com/OpnForm/OpnForm.git',
      subdir: 'plugins/opnform',
    },
    iconKey: 'opnform',
    capabilities: { skillCount: 1, mcpServerCount: 1, hasPulseExtension: false },
    installState: 'available',
  },
  {
    id: 'mobbin',
    name: 'Mobbin',
    description: 'Search real product screens, flows, and website sections. Requires a paid Mobbin plan.',
    author: { name: 'Mobbin', url: 'https://mobbin.com' },
    license: 'MIT',
    category: 'Design',
    featured: false,
    visibility: 'public',
    sourceFormat: 'agent-plugin',
    source: { kind: 'git', url: 'https://github.com/mobbin/mobbin-agent-plugin.git' },
    iconKey: 'mobbin',
    capabilities: { skillCount: 0, mcpServerCount: 1, hasPulseExtension: false },
    installState: 'available',
  },
];
